[project]
name = "vla-code-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.11"
dependencies = [
    "mani-skill>=3.0.0b20",
    "sapien>=3.0.0b1",
    "setuptools>=77.0.3",
    "torch>=2.6.0",
]
